import { Link } from "react-router-dom";
import "./LoginPage.css";
import { useSelector, useDispatch } from "react-redux";
import { useState, useEffect } from "react";
import { loginUser } from "../../features/auth/authSlice";
import { useNavigate } from "react-router-dom";
import Loader from "../../components/Loader/Loader";

const demoCredentials = {
  email: "jack@mail.com",
  password: "harsh@1234",
};

function LoginPage() {

  const navigate = useNavigate()
  const [email, setEmail] = useState("")
  const [password, setPassword] = useState("")

  const dispatch = useDispatch();
  const { isAuthenticated, loading, error } = useSelector((state) => state.auth);

  useEffect(() => {
    if (isAuthenticated) {
      navigate("/dashboard"); 
    }
  }, [isAuthenticated, navigate]);

  const handleSubmit = (e) => {
    e.preventDefault();
    dispatch(loginUser({email, password}));
  };

  const fillDemoCredentials = () => {
    setEmail(demoCredentials.email);
    setPassword(demoCredentials.password);
  };

  return (
    <>
      {loading ? <Loader /> : null}
      <div className="page page-login auth-page">
        <main className="page-main">
          <div className="container">
            <section className="auth-shell">
              <div className="card auth-hero login-hero">
                <div className="auth-hero-content">
                  <p className="eyebrow">Welcome Back</p>
                  <h1 className="display-title login-title">Sign in to continue building.</h1>
                  <p className="text-body login-copy">
                    Due to free hosting limits, live resume uploads and AI processing may not
                    complete reliably on the deployed app.
                  </p>
                  <p className="text-body login-copy">
                    To explore the application, use the demo account below. It includes reports
                    already generated by the project.
                  </p>

                  <div className="demo-login-box" aria-label="Demo account credentials">
                    <button
                      className="demo-credential"
                      type="button"
                      onClick={() => setEmail(demoCredentials.email)}
                    >
                      <span>Email</span>
                      <strong>{demoCredentials.email}</strong>
                    </button>
                    <button
                      className="demo-credential"
                      type="button"
                      onClick={() => setPassword(demoCredentials.password)}
                    >
                      <span>Password</span>
                      <strong>{demoCredentials.password}</strong>
                    </button>
                    <button
                      className="button button-secondary demo-fill-button"
                      type="button"
                      onClick={fillDemoCredentials}
                    >
                      Use demo account
                    </button>
                  </div>
                </div>

                <div className="auth-hero-footer">
                  <p className="text-muted auth-meta">
                    Click either credential to fill that field, or use the demo button to fill
                    both at once.
                  </p>
                </div>
              </div>

              <div className="card auth-panel">
                <div className="auth-panel-inner">
                  <div>
                    <p className="eyebrow">Login</p>
                    <h2 className="section-title">Enter your account</h2>
                  </div>

                  <form  onSubmit={handleSubmit} className="auth-form">
                    <div className="field-list">
                      <label className="field" htmlFor="login-email">
                        <span className="field-label">Email</span>
                        <input
                          className="input"
                          id="login-email"
                          onChange={(e)=> setEmail(e.target.value)}
                          type="email"
                          value={email}
                          placeholder="you@example.com"
                        />
                      </label>

                      <label className="field" htmlFor="login-password">
                        <span className="field-label">Password</span>
                        <input
                          className="input"
                          id="login-password"
                          type="password"
                          onChange={(e)=>setPassword(e.target.value)}
                          value={password}
                          placeholder="Enter your password"
                        />
                      </label>
                    </div>

                    <button className="button button-primary" type="submit">
                      {loading ? "Loading...." : "Login"}
                    </button>

                    {error ? <p className="form-error">{error}</p> : null}
                  </form>

                  <p className="text-body auth-switch">
                    Don&apos;t have an account?{" "}
                    <Link className="link-button" to="/signup">
                      Create one
                    </Link>
                  </p>

                  <Link className="link-button login-home-link" to="/">
                    Back to Home
                  </Link>
                </div>
              </div>
            </section>
          </div>
        </main>
      </div>
    </>
  );
}

export default LoginPage;
